### ISSUE TITLE
Restructuring of tutorials

### ISSUE THREAD

**Issue by ralph-lange** [micro-ROS/micro-ROS.github.io#143]
- [x] Some entry page explaining the structure of the tutorials  @ralph-lange 

Core Tutorials
- [x] "First micro-ROS application on Linux" @julibert, @FranFin @pablogs9 https://github.com/micro-ROS/micro-ROS.github.io/pull/150
    - [x] Assumption: First Linux laptop even without ROS.
    - [x] Point to Dockerfile at https://github.com/micro-ROS/docker/blob/dashing/base/Dockerfile 
    - [x] Steps to install ROS, micro-ROS do not have to be explained, but one sentence + link to instructions is enough
    - [x] Explain how to setup micro-ROS build tooling
    - [x] To create this page use https://micro-ros.github.io/docs/tutorials/advanced/linux/linux_getting_started/ as a basis and move it accordingly.
    - [x] Explain how to compile and run ping pong application.
    - [x] Explain the most important lines of code in this application and then refer to the separate "Programming with rcl and rclc tutorial".
- [x] "First micro-ROS application on an RTOS" @julibert , @FranFin, @pablogs9 https://github.com/micro-ROS/micro-ROS.github.io/pull/149
    - [x] Explain commands line for building and flashing by some "hello world"-like example for all three RTOS (by merging the contents from the FreeRTOS Getting Started and Zephyr Getting Started)
    - [x] Explain how to connect the board JTAG etc. (cf. https://micro-ros.github.io/docs/tutorials/advanced/nuttx/udp_echo/)
    - [x] Use ping-pong app as the first application
    - [x] Explain that our build system covers three RTOS
    - [x] Finally refer to https://github.com/micro-ROS/micro-ros-build/tree/dashing/micro_ros_setup for more information.
    - [x] Create this tutorial using https://micro-ros.github.io/docs/tutorials/advanced/nuttx/nuttx_getting_started/ as a starting point but move it to the core tutorials section.
    - [x] Also merge contents from https://micro-ros.github.io/docs/tutorials/advanced/nuttx/add_microros_config/ and then remove this page. @pablogs9: What should we do with Kconfig compatibility? Update: included.
- [ ] "Programming with rcl and rclc"  @ralph-lange, @JanStaschulat, @norro  
    - [x] Explain that we take most ROS 2 concepts to micro-ROS @ralph-lange 
    - [x] Explain how we build upon existing ROS 2 layers (rmw, rcl) @ralph-lange
    - [x] Explain rclc package with convenience functions @ralph-lange
    - [x] Explain that rclcpp might be also used on stronger MCUs (but not in scope of this tutorial) @ralph-lange
    - [x] Table of contents @ralph-lange
    - [x] Section on topics (pub/sub) @JanStaschulat 
    - [x] Section on services @FranFin 
    - [x] Section on timers @JanStaschulat 
    - [x] Section on the rclc Executor @JanStaschulat 
    - [ ] Section on parameters (who?)
    - [x] Section on lifecycle (aka managed nodes) @norro #179 
- [x] "Optimize middleware configuration"  @julibert 
    - [x] Make this page a real tutorial.
    - [x] Use ping-pong application as the running example (e.g., set number of services to zero)
    - [x] Remove list of all configuration parameters but refer either to some README.md in the corresponding repo or move the list to the concepts section of the website.
    - [x] Explain step by step where and how to change the configuration (in cmake).

Advanced Tutorials
- [x] "NuttX NSH console over USB or UART"  @julibert 
    * Merge the two existing tutorials
    * Shorten description how to build the application but refer to core tutorials  for these steps.
- [x] "6LoWPAN with micro-ROS on NuttX"  @julibert  
    * Merge the existing two pages on 6LoWPAN
- [x] "Debugging a NuttX target"  @tkolcon 
    * Merge the two existing tutorials
- [x] "Adding Micro-ROS to a NuttX board configuration"  @ralph-lange 
    * Just move to advanced tutorials section
- [x] "Zephyr Emulator"   @pablogs9  https://github.com/micro-ROS/micro-ROS.github.io/pull/154
    * State that again the ping-pong app is being used as a running example and that we assume that the reader knows how to build this app for Zephyr from the "First micro-ROS application on an RTOS".
    * Shorten this tutorial and only explain the steps that are different compared with the "First micro-ROS application on an RTOS"
- [x] "Getting started with ROS 2 tracing"   @ralph-lange 
    * Just move to advanced tutorials section
- [x] "Some tutorial on benchmarking"  @amx-piap 

Further TODOs
- [x] Remove udp and tcp server tutorials   @ralph-lange

**Comment by FranFin** [comment]
@ralph-lange: Closing this issue as the only task remaining is to create a "Section on parameters (who?)", and this feature is not implemented yet.

**Comment by ralph-lange** [comment]
@FranFin, yes, as soon as parameters have been implemented, a corresponding section should be added to https://micro-ros.github.io/docs/tutorials/core/programming_rcl_rclc/.
In my opinion there is no need to document this in an issue here as it should be normal to always add a section to this tutorial when implementing new features in rclc.
