### ISSUE TITLE
Refactor 'First micro-ROS Application on an RTOS' tutorial

### ISSUE THREAD

**Issue by ralph-lange** [micro-ROS/micro-ROS.github.io#167]
- Create separate pages (urls) for each RTOS (NuttX, FreeRTOS, and Zephyr)
- Ensure redirect from '/docs/tutorials/advanced/zephyr/zephyr_getting_started/'
- Avoid three completely separate pages but use includes to generate the pages from common sections
- Introduce a nice overview page to ask the reader to decide for one RTOS for this tutorial.

**Comment by ralph-lange** [comment]
@FranFin, no need to use Jinja2 for generating the three versions of the 'First micro-ROS application on an RTOS' from a common template. Jekyll provides include directives for this. I first tried [include_relative](https://jekyllrb.com/docs/includes/#including-files-relative-to-another-file), which works with Markdown and HTML, but there seems to be a [bug](https://talk.jekyllrb.com/t/include-relative-could-not-locate-the-included-file/3148) in the version 3.8.5.
As a fallback solution, I switched to a normal include, which refers to the `_includes` folder.

**Comment by ralph-lange** [comment]
I've pushed my very first changes to https://github.com/micro-ROS/micro-ROS.github.io/tree/feature/rtos-specific_tutorials_with_common_sections.

**Comment by ralph-lange** [comment]
Relates to https://github.com/micro-ROS/micro-ROS.github.io/issues/143.

**Comment by dayjaby** [comment]
+ Sample app link is broken for NuttX

**Comment by ralph-lange** [comment]
Fixed in https://github.com/micro-ROS/micro-ROS.github.io/commit/57dfe9f11ccaf90fff576d6ee317507bd9a2a666
