### ISSUE TITLE
Changing Webpage License from Apache 2.0 to Creative-Commons

### ISSUE THREAD

**Issue by FranFin** [micro-ROS/micro-ROS.github.io#207]
Hello contributors to the [micro-ROS webpage](https://micro-ros.github.io/)!

We are migrating the license to [Creative Commons Attribution-NoDerivatives 4.0 International (CC BY-ND 4.0)](https://creativecommons.org/licenses/by-nd/4.0/), which is fitter to the content of the page than the previously employed [Apache license 2.0](https://www.apache.org/licenses/LICENSE-2.0). We kindly ask all external people that contributed to the webpage development to confirm that they agree with this change of license terms: @aksakalli @rpcme @coliff @rjhcnf @jayhou @andre-nguyen @alsaibie.

If not notified otherwise within a two-weeks time slot, we will proceed to the change of license.

Best regards and thanks,
Francesca Finocchiaro

**Comment by andre-nguyen** [comment]
all good for me

**Comment by aksakalli** [comment]
all good

**Comment by rjhcnf** [comment]
Good to me.

**Comment by alsaibie** [comment]
All good

**Comment by ralph-lange** [comment]
@FranFin, please update the LICENSE file in the repo, too.

**Comment by ralph-lange** [comment]
@FranFin, also the README.md has to be updated, where I already added a paragraph explaining that the template comes under MIT license and mentioning the commits from where on we started to add our own contents which are under the new license.
