### ISSUE TITLE
Rework webpage

### ISSUE THREAD

**Issue by FranFin** [micro-ROS/micro-ROS.github.io#234]
Tasks regarding the webpage restructuring as discussed during the OFERA f2f meeting of 14.10.2020

- [x] Landing Page: Add a list of main features @ralph-lange 

- [ ] Overview section
    - [x] Architecture
        - [x] Update/rework Architecture diagram @ralph-lange 
        - [x] Link each layer to associated features, according to this [document](https://docs.google.com/document/d/1I-bDoI5YEKSdL-dbM8IDUghDALIzEOHCppiAPUIvC-A/edit) @ralph-lange 
        - [x] Remove ‘Source Code Repositories’ part, and move it to the ‘Docker and CI status’ @FranFin 
    - [x] Feature Status
        - [x] Now meant to represent comparison with features of ROS 2: change name accordingly @ralph-lange 
        - [x] Update/add/delete features. Missing: @ralph-lange 
            - Actions
            - Graphs
            - Parameters
            - Discovery
            - QoS?
            - p2p (or explain difference between new p2p and CED middleware)
            - Operations within a ROS 2 node
            - Support for RT code - add sentence regarding rclpy and rclcpp
        - [x] Add third column for symbols that encode features status [Done; Done partially; WIP; Not done but envisioned in the very near future; Not done and not planned] + Legend @FranFin 
        - [x] Split table into sub-tables: group features by category that +- represent the features list presented in 'Landing page' and ‘Architecture’. Small headings in bold between categories. @FranFin 
    - [x] Supported Hardware @pablogs9 ---> https://github.com/micro-ROS/micro-ROS.github.io/pull/241
        - [x] Change appearance: only logos, and then you get the info when clicking on the logo
        - [x] Add sentence explaining that more boards have been ported by users and link to table in micro_ros_setup README
    - [x] Supported RTOSes [page to be created]: Add RTOSes in the same form as the hardware, with clickable logos with short description (while removing them from ‘Concepts’ page) @FranFin 
    - [x] Transport and Data Links: Change the table to be more similar (or even equal) to the one that is found in the micro_ros_setup README (specifying which transports are allowed for each available combination of HW and RTOS) ---> https://github.com/micro-ROS/micro-ROS.github.io/pull/243 @pablogs9 
    - [x] Docker and CI status @jamoralp  -> #248
        - [x] Rename as ‘Repositories, Dockers and CI status’
        - [x] Add ‘Source Code Repositories’ part from ‘Architecture’, and update it
        - [x] Update Docker and CI status part
    - [x] Members, partners and users @FranFin 
        - [x] Add new partners and MW users
        - [x] Add 'Collaborators' section
    - [x] Licensing [page to be created]: Add category explaining micro-ROS' licenses @ralph-lange 

- [x] Concepts section
    - [x] Client library @ralph-lange 
        - [x] Intro to Client library
            - Rewrite text and Rework diagram
            - Reduce importance of rclcpp and specify that we don’t use it much
            - Introduce the rclc
            - rcl and rcutils: explain differences with respect to that of ROS 2
            - Link ‘Programming with rcl and rclc’ in the Tutorials section
        - [x] Embedded Transform: remove
        - [x] Decision paper -> moved to a PDF (as discussed in later OFERA meeting)
    - [x] Middleware
        - [x] Micro XRCE-DDS @FranFin 
            - Update text (e. g. mention FreeRTOS and Zephyr)
            - Link ‘Middleware Configuration’ in the Tutorials section
            - Mention rmw and link `rmw_microxrcedds` readme
            - Link to ‘custom QoS’ tutorials
            - Add memory profiling of Micro XRCE-DDS
        - [x] micro-ROS and FIWARE: move it to standalone section, under the name "Interoperability with FIWARE" @jamoralp  -> #249 
        - [x] micro-ROS compared to rosserial: change name to "Micro XRCE-DDS compared to rosserial" @FranFin 
    - [x] RTOS @FranFin 
        - [x] Why a Real-Time Operating System?: Add RTOSes logos at the end, that redirect to new pages in the Overview Section 
        - [x] FreeRTOS/NuttX/Zephyr: Remove and pass descriptions to Overview section
        - [x] Integration with colon: Remove. The sentence can be added to the only section that will be left (Why a Real-Time Operating System?)
    - [x] micro-ROS' build system [page to be added] ---> https://github.com/micro-ROS/micro-ROS.github.io/pull/244 @pablogs9 
        - [x] Section dedicated to standard build system
        - [x] Section dedicated to micro-ROS as a component in external development environments
    - [x] Benchmarking: Rework in order to provide results of benchmarking @amx-piap 
    - [x] micro-ROS memory profiling [page to be added]: material [here](https://www.eprosima.com/index.php/resources-all/performance/micro-ros-client-memory-profiling) @FranFin 

- [x] Tutorials section: NuttX-specific tutorials: Add a disclaimer specifying that they are currently unmaintained. ---> https://github.com/micro-ROS/micro-ROS.github.io/pull/242 @pablogs9 

- [ ] Demos section:
    - [x] Rewrite overview page 
    - [x] Add MoveIt demo @FranFin 
    - [ ] Add ROS 2 to micro-ROS TCP tunneling over WAN via IS demo @FranFin 
    - [x] Add PIAP demo @amx-piap

**Comment by ralph-lange** [comment]
The new feature list is now online at https://micro-ros.github.io//docs/overview/features/ with a collapsible layout. However, without any graphics the page is a bit boring. Two options:
1. Just add some graphics of an MCU to brighten up the page and create a separate page for the architecture overview.
2. Include the architecture diagram, but _below_ the list of features. I may squeeze the list of features and even make it a [accordion](https://jqueryui.com/accordion/). Of course, the page should be named "Features and Architecture" then.

What do you think, @FranFin?

**Comment by FranFin** [comment]
@ralph-lange I like it a lot! Maybe the formatting is too tight. Would it be possible to make it a little bit bigger?

**Comment by ralph-lange** [comment]
> 
> 
> @ralph-lange I like it a lot! Maybe the formatting is too tight. Would it be possible to make it a little bit bigger?

Done in https://github.com/micro-ROS/micro-ROS.github.io/commit/25c0051e37c8e91e1bb6df3925184f9ff8229b0b.

**Comment by ralph-lange** [comment]
@FranFin, regarding "Add third column for symbols that encode features status": I already added this column in https://github.com/micro-ROS/micro-ROS.github.io/pull/232/commits/aed04becee685527c64051934143e465b2ff2d10.
