### ISSUE TITLE
CI-build status for packages hosted at ros2/rclc

### ISSUE THREAD

**Issue by JanStaschulat** [micro-ROS/micro-ROS.github.io#250]
@ralph-lange @pablogs9 @FranFin 
I would like to have a status page for the releases of the packages in ros2/rclc:
The overview on https://micro-ros.github.io/docs/overview/docker_ci_status/ is only for the complete repository and only for arm64 architecture. I would like to create a table to have an overview, if a bloom release on ROS 2 build farm fails:

packages:

- rclc

- rclc_lifecycle

- rclc_examples

architectures:

- amd64

- armhf

- arm64

releases:

- Dashing

- Eloquent

- Foxy

- Rolling

Where could I create such a page?

- at micro-ros.github.org

- at ros2/rclc

What do you think?

**Comment by ralph-lange** [comment]
I propose to add it at both places: in the README.md in ros2/rclc as well as on the existing page on micro-ros.github.org. For the latter, a new section should be added given the different architectures, etc.

**Comment by jamoralp** [comment]
Hello @JanStaschulat, I recently opened a PR for reworking the CI status section. Maybe you could address these changes there? #248

**Comment by FranFin** [comment]
I back up the idea of adding the statuses for the releases of the `rclc` packages in the PR that @jamoralp is mentioning as well as in the README of the ros2/rclc repo.

**Comment by JanStaschulat** [comment]
Okay, I will add the table to  PR #248

**Comment by JanStaschulat** [comment]
created https://github.com/micro-ROS/micro-ROS.github.io/pull/253

**Comment by pablogs9** [comment]
All merged, I'm closing, reopen if needed
