### ISSUE TITLE
Middleware Configuration: dead link to 'generic/client-host-colcon.meta'

### ISSUE THREAD

**Issue by gavanderhoorn** [micro-ROS/micro-ROS.github.io#295]
As per subject.

The link `https://github.com/micro-ROS/micro_ros_setup/blob/foxy/micro_ros_setup/config/host/generic/client-host-colcon.meta` to the configuration of the `ping-pong` example application `404`s for me.

**Comment by gavanderhoorn** [comment]
Looks like it has one `micro_ros_setup/` too many?

**Comment by pablogs9** [comment]
Solved here https://github.com/micro-ROS/micro-ROS.github.io/pull/296

**Comment by gavanderhoorn** [comment]
Would a permalink perhaps be an idea?

Would avoid this situation from happening again.
