### ISSUE TITLE
script location for mciroROS agent  and rclc ping_pong

### ISSUE THREAD

**Issue by MARLARCHAN** [micro-ROS/micro-ROS.github.io#298]
Dear @pablogs9 

 I would like to know the script location inside microros code  for the following commands. If you know , can you guide me please.

1. $ros2 run micro_ros_agent micro_ros_agent serial --dev /dev/ttyUSB0 -v 6
2. $ros2 run micro_ros_demos_rclc ping_pong

Best Regards,
Marlar

**Comment by pablogs9** [comment]
None of them runs a script.

1. Runs a micro-ROS Agent executable
2. Runs the ping_pong demo executable on host.

**Comment by MARLARCHAN** [comment]
Dear @pablogs9 
I would like to know where can I find pingpong executable code on host?
