### ISSUE TITLE
Location of ping_pong executable code

### ISSUE THREAD

**Issue by MARLARCHAN** [micro-ROS/micro-ROS.github.io#299]
Dear @pablogs9

Where can I find pingpong executable code on host?

Best Regards,
Marlar

**Comment by pablogs9** [comment]
https://github.com/micro-ROS/micro-ROS-demos/blob/foxy/rclc/ping_pong/main.c

Please refer to the tutorials:

![image](https://user-images.githubusercontent.com/7647884/112274146-70225c00-8c7e-11eb-8188-2a36385bbe51.png)
