### ISSUE TITLE
Nuttx: XBEE: performance issue

### ISSUE THREAD

**Issue by amx-piap** [micro-ROS/micro-ROS.github.io#38]
When compiling the xbee driver using no optimisation, the she shell over USB (USB-ACM) will not work properly. 

Full optimisation must be enable to make it work.

**Comment by imuguruza** [comment]
Hi @amx-piap ,

I consider more appropriate to open an issue at [NuttX fork issues](https://github.com/micro-ROS/NuttX/issues)
