### ISSUE TITLE
Porting micro-ROS to a Proprietary Board with MIMXRT1062 Processor

### ISSUE THREAD

**Issue by EvelynSabbag** [micro-ROS/micro-ROS.github.io#400]
How can I port micro-ROS to a proprietary board with an NXP MIMXRT1062 processor? All the examples are built with eval boards. Also, I am using FreeRTOS.

**Comment by pablogs9** [comment]
Hello @EvelynSabbag here you have some tips: https://docs.vulcanexus.org/en/latest/rst/tutorials/micro/custom_platforms/custom_platforms.html

In any case, if you need professional support please contact support@eProsima.com
