### ISSUE TITLE
Overview Section Rework

### ISSUE THREAD

**Issue by imuguruza** [micro-ROS/micro-ROS.github.io#52]
- [ ] [Overview → Overview](https://micro-ros.github.io/docs/overview/) [mainly eProsima, some contributions by @ralph-lange]
      - Rename to “Overview → Architecture” or “Overview → Architectural Overview” @ralph-lange 
      - Remove the paragraph on tutorials as the link to tutorials is now placed prominently in the top navigation bar @ralph-lange 
      - Update architecture diagram. @ralph-lange  added new diagram
      - Revise lists of concepts and source code repos @ralph-lange 
      - Add matrix indicating release status of repos in the style of: https://uuvsimulator.github.io/ -> List of repositories
      - Prominently link to .repos file or some other entry point to a build from source

- [ ] [Overview → Hardware](https://micro-ros.github.io/docs/overview/hardware/) [ALR]
      - Add paragraph explaining that our stack can be brought to a number of platforms. Argue about use of Posix standard and point to large number of platforms supported by NuttX.

- [ ] [Overview → Comparison to other approaches to put ROS onto small embedded devices](https://micro-ros.github.io/docs/overview/comparison/) @iluetkeb 
      - Shorten title: What about “Comparison to other embedded ROS approaches”?
      - List and link further known approaches, e.g., mROS

**Comment by imuguruza** [comment]
> Overview → Hardware [ALR]
>Add paragraph explaining that our stack can be brought to a number of platforms. Argue about use of Posix standard and point to large number of platforms supported by NuttX.

I am thinking that makes more sense to add the explanations under "Concepts => RTOS", we could just put a small list and the link to the complete list at this section. Otherwise, we would mix concept explanation and the supported board list

**Comment by imuguruza** [comment]
>Overview → Hardware [ALR]
>Add paragraph explaining that our stack can be brought to a number of platforms. Argue about use of Posix standard and point to large number of platforms supported by NuttX.

Opened a [PR](https://github.com/micro-ROS/micro-ROS.github.io/pull/56) to improve it

**Comment by imuguruza** [comment]
Closed previous one an opened [a new on](https://github.com/micro-ROS/micro-ROS.github.io/pull/58)e, based on the new master that contains no-broken links

**Comment by ralph-lange** [comment]
Made large improvements to start page and main overview page in PR https://github.com/micro-ROS/micro-ROS.github.io/pull/63. Further changes to overview page needed by @julianbermudez et al., cf. this issue.

**Comment by ralph-lange** [comment]
Superseded by https://github.com/micro-ROS/micro-ROS.github.io/issues/107
