### ISSUE TITLE
Concept Section Rework

### ISSUE THREAD

**Issue by imuguruza** [micro-ROS/micro-ROS.github.io#53]
- [x] Introduce some overview page “Concepts → Overview” at the url [https://micro-ros.github.io//docs/concepts/](https://micro-ros.github.io//docs/concepts/) @ralph-lange 
      - Even introduced three submenus following the layering of micro-ROS.
- [x] [Concepts → Real-Time Operating System (RTOS)](https://micro-ros.github.io/docs/concepts/rtos/) @imuguruza 
      - Removed redundant heading.
      - Removed heading Introduction.
      - Floating NuttX logo.
      - Link to supported dev boards. Revised texts.
- [x] [Concepts → Client Library](https://micro-ros.github.io/docs/concepts/client_library/) @ralph-lange 
      - Revised text, prominently explain rcl vs. rclcpp API
      - Add colored diagram from Deliverable D1.5
- [x] [Concepts → Real-Time Executor](https://micro-ros.github.io/docs/concepts/client_library/real-time_executor/) @ralph-lange 
      - Update text with text modules from Deliverable D1.5, in particular introduce subsections on static scheduling
      - Link to real-time working group (?)
      - Reduce or move details of callback-group-level executor
- [x] [Concepts → System Modes](https://micro-ros.github.io/docs/concepts/client_library/system_modes/) @norro 
      - Update text with text modules from Deliverable D1.5
      - Add prominent note on on-going port of diagnostics
- [ ] Concepts → Middleware @julianbermudez 
      - Fill new page at https://micro-ros.github.io/docs/concepts/middleware/Micro_XRCE-DDS/
- [ ] Concepts → Benchmarking @tkolcon 
      - Fill new page at https://micro-ros.github.io/docs/concepts/benchmarking/
      - Create subpages if necessary.

**Comment by ralph-lange** [comment]
Superseded by https://github.com/micro-ROS/micro-ROS.github.io/issues/108
