### ISSUE TITLE
Start Page Rework

### ISSUE THREAD

**Issue by imuguruza** [micro-ROS/micro-ROS.github.io#55]
+ Fix links on start page [@ralph-lange ].
  + GitLab CI could help you: https://gitlab.com/micro-ROS/ci-support/micro-ROS-github-io/-/jobs/227034779
  + Can run it locally with a script.
  + We should enforce these checks before merging to master.

**Comment by ralph-lange** [comment]
Hi @imuguruza, thank you very much for converting my list of findings to issues and for resolving this one. This issue can be closed now.
